language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - ./ci/initialize-ci.sh $ORIENTDB_VERSION
  - composer install --prefer-source

script: ./vendor/bin/phpunit

env:
  - ORIENTDB_VERSION=1.7-rc2
  - ORIENTDB_VERSION=1.7-SNAPSHOT

matrix:
  allow_failures:
    - env: ORIENTDB_VERSION=1.7-SNAPSHOT
